/* =============================================
   phrases.js — 最短英会話モード フレーズデータ
   ワーホリ・留学でよく使う表現
   ============================================= */

const CONVO_LEVELS = [
  {
    id: 'convo_beginner',
    level: 1,
    label: 'すぐ使える',
    color: '#FF9500',
    bg: '#FFF5E6',
    icon: 'ti-message-circle',
    desc: '挨拶・注文・基本のやりとり',
    phrases: [
      { jp: 'こんにちは、元気ですか？',   answers: ['Hi, how are you?', 'Hey, how are you?', 'Hello, how are you?'] },
      { jp: 'お名前はなんですか？',         answers: ['What is your name?', "What's your name?"] },
      { jp: '出身地はどこですか？',         answers: ['Where are you from?', 'Where do you come from?'] },
      { jp: 'どこに住んでいますか？',       answers: ['Where do you live?', 'Where are you living?'] },
      { jp: '元気ですか？',                 answers: ['How are you?', 'How are you doing?', "How's it going?"] },
      { jp: 'はじめまして',                 answers: ['Nice to meet you.', 'Good to meet you.', 'Pleased to meet you.'] },
      { jp: 'お仕事は何をしていますか？',   answers: ['What do you do?', 'What do you do for work?', 'What do you do for a living?'] },
      { jp: '○○語を話しますか？',           answers: ['Do you speak ○○?', 'Can you speak ○○?'] },
      { jp: 'これをください',               answers: ["I'll have this, please.", 'I would like this, please.', 'Can I get this, please?'] },
      { jp: 'お会計をお願いします',         answers: ['Could I have the check, please?', 'Can I have the bill, please?', 'Check, please.'] },
      { jp: '何時ですか？',                 answers: ['What time is it?', 'Do you know what time it is?'] },
      { jp: 'どの○○ですか？',               answers: ['Which ○○?', 'Which one is ○○?'] },
      { jp: 'ここ座って良い？',             answers: ['Can I sit here?', 'Is this seat taken?', 'Is anyone sitting here?'] },
      { jp: '質問してもいいですか？',       answers: ['Can I ask you a question?', 'May I ask you something?', 'Do you mind if I ask you something?'] },
      { jp: 'わかりません',                 answers: ["I don't know.", "I'm not sure.", 'No idea.'] },
      { jp: 'どの階？',                     answers: ['Which floor?', 'What floor?'] },
      { jp: 'なんでもいいよ',               answers: ['Anything is fine.', "I don't mind.", 'Either way is fine.'] },
      { jp: 'ここで食べます',               answers: ['For here.', "I'll eat here.", 'Dining in.'] },
      { jp: '持ち帰りでお願いします',       answers: ['To go.', 'Takeaway, please.', 'To take out, please.'] },
      { jp: 'どうだった？',                 answers: ['How was it?', 'How did it go?', 'How did you find it?'] },
      { jp: '（英語が）わかりません',       answers: ["I don't understand.", 'I do not understand.'] },
      { jp: '注文お願いします',             answers: ['Could you take my order?', 'Can I order?', 'I would like to order.'] },
      { jp: 'これをください（レストランで）', answers: ["I'll have this one.", 'I will have this one.', 'I would like this one.'] },
      { jp: '以上です',                     answers: ["That's all.", 'That is all.', 'That will be all.'] },
      { jp: '会計お願いします',             answers: ['Check, please.', 'Can I have the check?', 'Could I have the bill, please?'] },
      { jp: 'クレジットカードを使えますか？', answers: ['Do you accept credit cards?', 'Can I pay by credit card?', 'Do you take credit cards?'] },
      { jp: '見ているだけです',             answers: ["I'm just looking, thank you.", 'Just looking, thanks.', "I'm just browsing, thank you."] },
    ]
  },
  {
    id: 'convo_intermediate',
    level: 2,
    label: '旅行・日常会話',
    color: '#34C759',
    bg: '#EDFAF2',
    icon: 'ti-plane',
    desc: 'ホテル・道案内・自己紹介の深掘り',
    phrases: [
      { jp: 'もう一度言ってください',             answers: ['Sorry?', 'Could you say that again?', 'Could you repeat that, please?', 'Pardon?'] },
      { jp: 'ゆっくり話してもらえますか？',       answers: ['Could you speak more slowly?', 'Could you speak slowly, please?', 'Can you slow down a bit, please?'] },
      { jp: 'わかりました（了解）',               answers: ['I got it.', 'Got it.', 'I understand.', 'Understood.'] },
      { jp: '会計は別々にしていただけますか？',   answers: ['Could we have separate checks?', 'Can we pay separately?', 'Could we get separate bills?'] },
      { jp: '荷物を預かっていただけますか？',     answers: ['Could you keep my baggage?', 'Could you store my luggage?', 'Can I leave my bags here?'] },
      { jp: '荷物を受け取りたいです',             answers: ["I'd like to pick up my baggage.", 'I would like to collect my luggage.', 'I need to pick up my bags.'] },
      { jp: 'なるほど、理解できます',             answers: ['That makes sense.', 'I see.', 'Got it.'] },
      { jp: '残念ですね',                         answers: ["That's a pity.", "That's too bad.", 'What a shame.'] },
      { jp: '気にしなくていいよ',                 answers: ["It doesn't matter.", "Don't worry about it.", 'No worries.'] },
      { jp: 'ただの勘だよ',                       answers: ["It's just a hunch.", 'Just a gut feeling.', 'Just a guess.'] },
      { jp: 'なんとなくそう思う',                 answers: ["It's just a feeling.", 'I just have a feeling.', 'I kind of feel that way.'] },
      { jp: 'Ryoの名前で予約しています',         answers: ["I have a reservation under the name Ryo.", "I've got a booking under Ryo."] },
      { jp: 'チェックインしたいです',             answers: ["I'd like to check in.", "I'm here to check in.", 'Can I check in, please?'] },
      { jp: 'チェックアウトは何時ですか？',       answers: ['What time is check-out?', 'What time do I need to check out?'] },
      { jp: '朝食は含まれていますか？',           answers: ['Is breakfast included?', 'Does it include breakfast?'] },
      { jp: 'チェックアウトしたいです',           answers: ["I'd like to check out.", "I'm ready to check out.", 'Can I check out, please?'] },
      { jp: 'カードで支払えますか？',             answers: ['Can I pay by card?', 'Do you accept card?', 'Do you take credit cards?'] },
      { jp: 'どのくらいここにいるんですか？',     answers: ['How long have you been here?', 'How long are you staying here?'] },
      { jp: 'なぜ○○語を勉強していますか？',       answers: ['Why are you studying ○○?', "What made you start studying ○○?"] },
      { jp: '趣味はなんですか？',                 answers: ['What are your hobbies?', 'What do you do for fun?', 'What do you like to do in your spare time?'] },
      { jp: '○○したことはありますか？',           answers: ['Have you ever ○○?', 'Have you tried ○○?'] },
      { jp: '○○が好きですか？',                   answers: ['Do you like ○○?', 'Are you into ○○?'] },
      { jp: '○○はどういう意味ですか？',           answers: ['What does ○○ mean?', 'What is the meaning of ○○?'] },
      { jp: '○○はいくらですか？',                 answers: ['How much is ○○?', 'How much does ○○ cost?'] },
      { jp: '○○に行きたいです',                   answers: ['I want to go to ○○.', "I'd like to go to ○○.", "I'd love to visit ○○."] },
      { jp: '○○まではどうやって行きますか？',     answers: ['How do I get to ○○?', 'What is the best way to get to ○○?'] },
      { jp: 'おすすめはなんですか？',             answers: ['Do you have any recommendations?', 'What would you recommend?', 'What do you suggest?'] },
      { jp: '話せて楽しかったです！',             answers: ['It was nice talking to you!', 'Great talking to you!', 'I enjoyed talking with you!'] },
      { jp: '一緒に行かない？',                   answers: ['Do you want to go together?', 'Want to come with me?', 'Why not come along?'] },
      { jp: '週末何か予定ある？',                 answers: ['Do you have any plans for the weekend?', 'Are you doing anything this weekend?', 'What are you up to this weekend?'] },
      { jp: '普段の自由時間は何をしていますか？', answers: ['What do you usually do in your free time?', 'How do you usually spend your free time?'] },
      { jp: '酔ってます',                         answers: ["I'm drunk.", "I'm a bit tipsy.", "I've had too much to drink."] },
      { jp: '愛知県出身です',                     answers: ["I'm from Aichi, Japan.", 'I come from Aichi, Japan.'] },
      { jp: '名古屋はトヨタや製造業で有名です',   answers: ['Nagoya is famous for Toyota and manufacturing.', 'Nagoya is well-known for Toyota and its manufacturing industry.'] },
      { jp: 'もっと早く起きればよかった',         answers: ['I should have woken up earlier.', 'I wish I had woken up earlier.'] },
      { jp: '雨が降り始めたらどうする？',         answers: ['What if it starts raining?', 'What should we do if it starts to rain?'] },
    ]
  },
  {
    id: 'convo_advanced',
    level: 3,
    label: '一歩上の表現',
    color: '#AF52DE',
    bg: '#F5EEFF',
    icon: 'ti-star',
    desc: 'ニュアンス・感情・自然な英語',
    phrases: [
      { jp: 'この場所よく知らない',                                   answers: ["I'm not familiar with this place.", "I don't know this area well.", "I don't really know this place."] },
      { jp: '私の英語はあまり上手ではありませんが、少し話しませんか？', answers: ["My English isn't very good, but would you like to talk a little?", "I'm not great at English, but shall we chat a bit?"] },
      { jp: '外国人の友達を作りたいけど、英語は少ししか話せません',       answers: ['I want to make foreign friends, but I can only speak English at a basic level.', "I'd love to make foreign friends, though my English is still basic."] },
      { jp: '昨日急に体調が悪くなって、早退しました',               answers: ['I suddenly felt unwell yesterday and had to leave school early.', 'I came down with something suddenly yesterday and had to leave early.'] },
      { jp: '全身がだるくて、吐き気がありました',                   answers: ['I felt weak all over and nauseous.', 'My whole body felt heavy and I was nauseous.'] },
      { jp: '人それぞれ考え方は違うと思います',                       answers: ['I think everyone has their own way of thinking.', 'Everyone thinks differently, I believe.', 'I think people all have their own perspectives.'] },
      { jp: 'ここが人気なのも納得',                                   answers: ['No wonder this place is so popular!', "It's no surprise this place is so popular!", 'I can see why this place is so popular!'] },
      { jp: 'カフェというより倉庫って感じ',                           answers: ["It's more like a warehouse than a café.", 'It feels more like a warehouse than a café.'] },
      { jp: 'つまり、待っていればいいんですね？',                     answers: ['So, I just need to wait, right?', "So all I have to do is wait, right?", 'So basically I just wait?'] },
      { jp: 'ジョリビーに行ったことがないから行ってみたい',           answers: ["I've never been to Jollibee, so I want to try it!", "I haven't been to Jollibee yet, so I'd love to give it a try!"] },
      { jp: '今度韓国に行くとき案内してほしい！',                     answers: ['Then next time I travel to Korea, I want you to show me around.', 'If I ever go to Korea, I would love for you to show me around!'] },
      { jp: '日本の賃金はフィリピンより高いですが、物価も高いです',   answers: ['Japan has higher wages than the Philippines, but the cost of living is also high.', 'Wages in Japan are higher than in the Philippines, but so is the cost of living.'] },
      { jp: '天気予報を確認しておくべきだった',                       answers: ['I should have checked the weather forecast.', 'I wish I had checked the weather forecast.'] },
      { jp: '思ってたより人が多い',                                   answers: ['There are more people than I expected.', "It's more crowded than I thought.", 'Way more people than I expected.'] },
      { jp: '思ってたより空いてる',                                   answers: ["It's less crowded than I expected.", "It's not as busy as I thought.", 'Way fewer people than I expected.'] },
      { jp: '彼女は偉そうな態度をしていた',                           answers: ['She had an arrogant attitude.', 'She was acting really arrogant.', 'She was being so full of herself.'] },
      { jp: '見ててハラハラする',                                     answers: ['It makes me nervous to watch.', "I can't watch without getting anxious.", "It's nerve-wracking to watch."] },
      { jp: 'なんでこんなの頼んだの？',                               answers: ['Why did you order something like this?', 'What made you order this?', 'Why on earth did you order this?'] },
    ]
  }
];
