/* =============================================
   quest_special.js — English Quest Special Level問題データ
   ============================================= */

const QUEST_SPECIAL = [

  /* ── TOEICビジネス単語（1択クイズ） ── */
  {type:'qz1',jp:'法律',en:'legislation',opts:['legislation','shipment','receipt','overtime']},
  {type:'qz1',jp:'欠員・空き',en:'vacancy',opts:['vacancy','surplus','deadline','signature']},
  {type:'qz1',jp:'今後の',en:'upcoming',opts:['upcoming','quarterly','fiscal','occasional']},
  {type:'qz1',jp:'重役',en:'executive',opts:['executive','blueprint','turnover','payroll']},
  {type:'qz1',jp:'保証・保証書',en:'warranty',opts:['warranty','dividend','subsidy','inventory']},
  {type:'qz1',jp:'手続き・手順',en:'procedure',opts:['procedure','trademark','outsource','benchmark']},
  {type:'qz1',jp:'不動産・資産',en:'property',opts:['property','auditor','franchise','payroll']},
  {type:'qz1',jp:'内線・延長',en:'extension',opts:['extension','shipment','surplus','turnover']},
  {type:'qz1',jp:'パンフレット',en:'brochure',opts:['brochure','receipt','deadline','blueprint']},
  {type:'qz1',jp:'頻繁な',en:'frequent',opts:['frequent','urgent','portable','flexible']},
  {type:'qz1',jp:'入場・入場料',en:'admission',opts:['admission','overtime','signature','inventory']},
  {type:'qz1',jp:'照会・照会先',en:'reference',opts:['reference','surplus','payroll','shipment']},
  {type:'qz1',jp:'地区',en:'district',opts:['district','deadline','receipt','trademark']},
  {type:'qz1',jp:'評判',en:'reputation',opts:['reputation','blueprint','overtime','subsidy']},
  {type:'qz1',jp:'かなりの',en:'substantial',opts:['substantial','glossy','durable','bilateral']},
  {type:'qz1',jp:'戦略',en:'strategy',opts:['strategy','turnover','shipment','dividend']},
  {type:'qz1',jp:'理想的な',en:'ideal',opts:['ideal','interim','mandatory','cumulative']},
  {type:'qz1',jp:'心配・懸念',en:'concern',opts:['concern','payroll','surplus','receipt']},
  {type:'qz1',jp:'任務・職務・関税',en:'duty',opts:['duty','inventory','deadline','overtime']},
  {type:'qz1',jp:'証拠・証明',en:'proof',opts:['proof','signature','blueprint','turnover']},
  {type:'qz1',jp:'定員・能力',en:'capacity',opts:['capacity','subsidy','receipt','payroll']},
  {type:'qz1',jp:'機関・団体',en:'institution',opts:['institution','franchise','shipment','surplus']},
  {type:'qz1',jp:'貴重な',en:'valuable',opts:['valuable','quarterly','urgent','bilateral']},
  {type:'qz1',jp:'苦情・不満',en:'complaint',opts:['complaint','benchmark','deadline','receipt']},
  {type:'qz1',jp:'割合・率・評価する',en:'rate',opts:['rate','auditor','overtime','blueprint']},
  {type:'qz1',jp:'外装',en:'exterior',opts:['exterior','dividend','signature','inventory']},
  {type:'qz1',jp:'内装',en:'interior',opts:['interior','trademark','payroll','shipment']},
  {type:'qz1',jp:'収入',en:'revenue',opts:['revenue','outsource','surplus','receipt']},
  {type:'qz1',jp:'布・生地',en:'fabric',opts:['fabric','turnover','deadline','overtime']},
  {type:'qz1',jp:'労働・労働者',en:'labor',opts:['labor','inventory','blueprint','payroll']},
  {type:'qz1',jp:'欠点・傷',en:'flaw',opts:['flaw','shipment','subsidy','signature']},
  {type:'qz1',jp:'電化製品',en:'appliance',opts:['appliance','receipt','franchise','deadline']},
  {type:'qz1',jp:'肥料',en:'fertilizer',opts:['fertilizer','overtime','benchmark','surplus']},
  {type:'qz1',jp:'続編',en:'sequel',opts:['sequel','payroll','auditor','shipment']},
  {type:'qz1',jp:'悪天候',en:'inclement weather',opts:['inclement weather','surplus','deadline','turnover']},
  {type:'qz1',jp:'母国の・ネイティブ',en:'native',opts:['native','fiscal','portable','mandatory']},
  {type:'qz1',jp:'収入',en:'income',opts:['income','outsource','benchmark','surplus']},
  {type:'qz1',jp:'節約・貯蓄',en:'saving',opts:['saving','receipt','overtime','blueprint']},
  {type:'qz1',jp:'調査結果',en:'findings',opts:['findings','shipment','payroll','deadline']},
  {type:'qz1',jp:'見つける・位置づける',en:'locate',opts:['locate','turnover','dividend','inventory']},
  {type:'qz1',jp:'延期する',en:'postpone',opts:['postpone','surplus','receipt','trademark']},
  {type:'qz1',jp:'証明する',en:'prove',opts:['prove','auditor','outsource','payroll']},
  {type:'qz1',jp:'正確な',en:'exact',opts:['exact','quarterly','fiscal','occasional']},
  {type:'qz1',jp:'得る・増加',en:'gain',opts:['gain','signature','blueprint','overtime']},
  {type:'qz1',jp:'注意深く・密接に',en:'closely',opts:['closely','urgent','portable','flexible']},
  {type:'qz1',jp:'特定する',en:'identify',opts:['identify','subsidy','receipt','payroll']},
  {type:'qz1',jp:'忠実な',en:'loyal',opts:['loyal','glossy','durable','bilateral']},
  {type:'qz1',jp:'ストレス・強調する',en:'stress',opts:['stress','shipment','turnover','deadline']},
  {type:'qz1',jp:'分析する',en:'analyze',opts:['analyze','inventory','surplus','receipt']},
  {type:'qz1',jp:'手数料・委員会',en:'commission',opts:['commission','blueprint','overtime','signature']},
  {type:'qz1',jp:'献身的な・責任感のある',en:'committed',opts:['committed','interim','mandatory','cumulative']},
  {type:'qz1',jp:'比較',en:'comparison',opts:['comparison','payroll','shipment','deadline']},
  {type:'qz1',jp:'部品・構成要素',en:'component',opts:['component','franchise','surplus','receipt']},
  {type:'qz1',jp:'可能にする',en:'enable',opts:['enable','auditor','turnover','overtime']},
  {type:'qz1',jp:'楽しい',en:'enjoyable',opts:['enjoyable','quarterly','fiscal','occasional']},
  {type:'qz1',jp:'既存の',en:'existing',opts:['existing','urgent','portable','flexible']},
  {type:'qz1',jp:'チラシ',en:'flyer',opts:['flyer','dividend','subsidy','inventory']},
  {type:'qz1',jp:'進む・続行する',en:'proceed',opts:['proceed','trademark','outsource','benchmark']},
  {type:'qz1',jp:'防ぐ',en:'prevent',opts:['prevent','auditor','franchise','payroll']},
  {type:'qz1',jp:'よく似て',en:'alike',opts:['alike','shipment','surplus','turnover']},
  {type:'qz1',jp:'任命する',en:'appoint',opts:['appoint','receipt','deadline','blueprint']},
  {type:'qz1',jp:'つながり・接続',en:'connection',opts:['connection','overtime','signature','inventory']},
  {type:'qz1',jp:'熱心な',en:'eager',opts:['eager','surplus','payroll','shipment']},
  {type:'qz1',jp:'楽にする・安心',en:'ease',opts:['ease','quarterly','urgent','bilateral']},
  {type:'qz1',jp:'かなり・公平に',en:'fairly',opts:['fairly','benchmark','deadline','receipt']},
  {type:'qz1',jp:'完全に・絶対に',en:'absolutely',opts:['absolutely','auditor','overtime','blueprint']},
  {type:'qz1',jp:'雰囲気',en:'atmosphere',opts:['atmosphere','dividend','signature','inventory']},
  {type:'qz1',jp:'計算する',en:'calculate',opts:['calculate','trademark','payroll','shipment']},
  {type:'qz1',jp:'対比・対照',en:'contrast',opts:['contrast','outsource','surplus','receipt']},
  {type:'qz1',jp:'監視する',en:'monitor',opts:['monitor','turnover','deadline','overtime']},
  {type:'qz1',jp:'時々',en:'occasionally',opts:['occasionally','inventory','blueprint','payroll']},
  {type:'qz1',jp:'実用的な',en:'practical',opts:['practical','shipment','subsidy','signature']},
  {type:'qz1',jp:'深刻な・真面目な',en:'serious',opts:['serious','receipt','franchise','deadline']},

  /* ── TOEICビジネス単語（単語入力式）── */
  {type:'word_input',jp:'〜するつもりだ',en:'intend to do'},
  {type:'word_input',jp:'同封する',en:'enclose'},
  {type:'word_input',jp:'実行する',en:'conduct'},
  {type:'word_input',jp:'尋ねる・問い合わせる',en:'inquire'},
  {type:'word_input',jp:'制限する',en:'restrict'},
  {type:'word_input',jp:'幅広い',en:'extensive'},
  {type:'word_input',jp:'しっかりと・安全に',en:'securely'},
  {type:'word_input',jp:'配布する・流通させる',en:'distribute'},
  {type:'word_input',jp:'全体の',en:'entire'},
  {type:'word_input',jp:'〜に関する',en:'regarding'},
  {type:'word_input',jp:'紹介',en:'referral'},
  {type:'word_input',jp:'作り出す・開発する',en:'develop'},
  {type:'word_input',jp:'拡大する・進出する',en:'expand'},
  {type:'word_input',jp:'造園',en:'landscaping'},
  {type:'word_input',jp:'〜する意思（気）がある',en:'willing'},
  {type:'word_input',jp:'称える・敬意・名誉',en:'honor'},
  {type:'word_input',jp:'認める・与える・許可する',en:'grant'},
  {type:'word_input',jp:'称賛する・褒める',en:'praise'},
  {type:'word_input',jp:'保証する・請け合う',en:'assure'},
  {type:'word_input',jp:'複雑な',en:'complicated'},
  {type:'word_input',jp:'はっきりと',en:'noticeably'},
  {type:'word_input',jp:'限定で',en:'exclusively'},
  {type:'word_input',jp:'緊急に',en:'urgently'},
  {type:'word_input',jp:'予想する',en:'anticipate'},
  {type:'word_input',jp:'収容する',en:'accommodate'},
  {type:'word_input',jp:'〜する余裕がある',en:'afford'},
  {type:'word_input',jp:'起こる・生じる・行われる',en:'occur'},
  {type:'word_input',jp:'保護する・保存する',en:'preserve'},
  {type:'word_input',jp:'〜にもかかわらず',en:'despite'},
  {type:'word_input',jp:'染料・染める',en:'dye'},
  {type:'word_input',jp:'しっかりと',en:'firmly'},
  {type:'word_input',jp:'わずかに',en:'marginally'},
  {type:'word_input',jp:'みなす・評価・関心',en:'regard'},
  {type:'word_input',jp:'値する',en:'deserve'},
  {type:'word_input',jp:'有望な',en:'promising'},
  {type:'word_input',jp:'順守する',en:'comply'},
  {type:'word_input',jp:'集中の妨げ',en:'distraction'},
  {type:'word_input',jp:'〜で有名',en:'be renowned for'},
  {type:'word_input',jp:'手頃な価格の',en:'affordable'},
  {type:'word_input',jp:'正確に',en:'precisely'},
  {type:'word_input',jp:'熟練した',en:'accomplished'},
  {type:'word_input',jp:'〜を取り除く',en:'eliminate'},
  {type:'word_input',jp:'Xを順守する',en:'comply with X'},
  {type:'word_input',jp:'徹底的な・几帳面な',en:'thorough'},
  {type:'word_input',jp:'〜を補充する',en:'replenish'},
  {type:'word_input',jp:'〜を上回る',en:'surpass'},
  {type:'word_input',jp:'楽観的な',en:'optimistic'},
  {type:'word_input',jp:'過度に',en:'excessively'},
  {type:'word_input',jp:'急な',en:'steep'},
  {type:'word_input',jp:'〜に登る',en:'ascend'},
  {type:'word_input',jp:'礼儀正しい',en:'courteous'},
  {type:'word_input',jp:'人口が密集している',en:'densely populated'},
  {type:'word_input',jp:'勤勉に',en:'industriously'},

  /* ── 不規則動詞（過去形を入力）── */
  {type:'irreg_past',base:'be',past:'was/were',pp:'been'},
  {type:'irreg_past',base:'become',past:'became',pp:'become'},
  {type:'irreg_past',base:'begin',past:'began',pp:'begun'},
  {type:'irreg_past',base:'blow',past:'blew',pp:'blown'},
  {type:'irreg_past',base:'break',past:'broke',pp:'broken'},
  {type:'irreg_past',base:'bring',past:'brought',pp:'brought'},
  {type:'irreg_past',base:'build',past:'built',pp:'built'},
  {type:'irreg_past',base:'buy',past:'bought',pp:'bought'},
  {type:'irreg_past',base:'catch',past:'caught',pp:'caught'},
  {type:'irreg_past',base:'choose',past:'chose',pp:'chosen'},
  {type:'irreg_past',base:'come',past:'came',pp:'come'},
  {type:'irreg_past',base:'cost',past:'cost',pp:'cost'},
  {type:'irreg_past',base:'cut',past:'cut',pp:'cut'},
  {type:'irreg_past',base:'deal',past:'dealt',pp:'dealt'},
  {type:'irreg_past',base:'do',past:'did',pp:'done'},
  {type:'irreg_past',base:'draw',past:'drew',pp:'drawn'},
  {type:'irreg_past',base:'drink',past:'drank',pp:'drunk'},
  {type:'irreg_past',base:'drive',past:'drove',pp:'driven'},
  {type:'irreg_past',base:'eat',past:'ate',pp:'eaten'},
  {type:'irreg_past',base:'fall',past:'fell',pp:'fallen'},
  {type:'irreg_past',base:'feel',past:'felt',pp:'felt'},
  {type:'irreg_past',base:'find',past:'found',pp:'found'},
  {type:'irreg_past',base:'fly',past:'flew',pp:'flown'},
  {type:'irreg_past',base:'forget',past:'forgot',pp:'forgotten'},
  {type:'irreg_past',base:'get',past:'got',pp:'got'},
  {type:'irreg_past',base:'give',past:'gave',pp:'given'},
  {type:'irreg_past',base:'go',past:'went',pp:'gone'},
  {type:'irreg_past',base:'grow',past:'grew',pp:'grown'},
  {type:'irreg_past',base:'have',past:'had',pp:'had'},
  {type:'irreg_past',base:'hear',past:'heard',pp:'heard'},
  {type:'irreg_past',base:'hit',past:'hit',pp:'hit'},
  {type:'irreg_past',base:'hold',past:'held',pp:'held'},
  {type:'irreg_past',base:'keep',past:'kept',pp:'kept'},
  {type:'irreg_past',base:'know',past:'knew',pp:'known'},
  {type:'irreg_past',base:'leave',past:'left',pp:'left'},
  {type:'irreg_past',base:'lend',past:'lent',pp:'lent'},
  {type:'irreg_past',base:'let',past:'let',pp:'let'},
  {type:'irreg_past',base:'lose',past:'lost',pp:'lost'},
  {type:'irreg_past',base:'make',past:'made',pp:'made'},
  {type:'irreg_past',base:'meet',past:'met',pp:'met'},
  {type:'irreg_past',base:'pay',past:'paid',pp:'paid'},
  {type:'irreg_past',base:'put',past:'put',pp:'put'},
  {type:'irreg_past',base:'read',past:'read',pp:'read'},
  {type:'irreg_past',base:'ride',past:'rode',pp:'ridden'},
  {type:'irreg_past',base:'ring',past:'rang',pp:'rung'},
  {type:'irreg_past',base:'run',past:'ran',pp:'run'},
  {type:'irreg_past',base:'say',past:'said',pp:'said'},
  {type:'irreg_past',base:'see',past:'saw',pp:'seen'},
  {type:'irreg_past',base:'sell',past:'sold',pp:'sold'},
  {type:'irreg_past',base:'send',past:'sent',pp:'sent'},
  {type:'irreg_past',base:'set',past:'set',pp:'set'},
  {type:'irreg_past',base:'sing',past:'sang',pp:'sung'},
  {type:'irreg_past',base:'sit',past:'sat',pp:'sat'},
  {type:'irreg_past',base:'sleep',past:'slept',pp:'slept'},
  {type:'irreg_past',base:'speak',past:'spoke',pp:'spoken'},
  {type:'irreg_past',base:'spend',past:'spent',pp:'spent'},
  {type:'irreg_past',base:'stand',past:'stood',pp:'stood'},
  {type:'irreg_past',base:'steal',past:'stole',pp:'stolen'},
  {type:'irreg_past',base:'swim',past:'swam',pp:'swum'},

  /* ── 生活・旅行英語（1択クイズ）── */
  {type:'qz1',jp:'集合住宅の1部屋（英国英語）',en:'flat',opts:['flat','deadline','dividend','receipt']},
  {type:'qz1',jp:'壁を共有している一軒家',en:'terraced house',opts:['terraced house','blueprint','trademark','overtime']},
  {type:'qz1',jp:'公共料金（水道・ガス・ネット）',en:'utilities',opts:['utilities','surplus','outsource','payroll']},
  {type:'qz1',jp:'路面電車',en:'tram',opts:['tram','signature','inventory','deadline']},
  {type:'qz1',jp:'交差点',en:'intersection',opts:['intersection','shipment','turnover','receipt']},
  {type:'qz1',jp:'途中下車・一時滞在',en:'stopover',opts:['stopover','shipment','receipt','overtime']},
  {type:'qz1',jp:'内見する',en:'see the flat',opts:['see the flat','surplus','deadline','signature']},
  {type:'qz1',jp:'中古の（やわらかい表現）',en:'pre-loved',opts:['pre-loved','blueprint','turnover','payroll']},
  {type:'qz1',jp:'観光スポット',en:'tourist attractions',opts:['tourist attractions','dividend','subsidy','inventory']},

  /* ── 性格・感情（1択クイズ）── */
  {type:'qz1',jp:'外向的な・社交的な',en:'extroverted',opts:['extroverted','fiscal','portable','mandatory']},
  {type:'qz1',jp:'野心的な',en:'ambitious',opts:['ambitious','occasional','durable','interim']},
  {type:'qz1',jp:'反抗的な',en:'rebellious',opts:['rebellious','quarterly','fiscal','occasional']},
  {type:'qz1',jp:'無神経な・鈍感な',en:'insensitive',opts:['insensitive','urgent','portable','flexible']},
  {type:'qz1',jp:'共感できる',en:'relatable',opts:['relatable','glossy','durable','bilateral']},
  {type:'qz1',jp:'孤立した',en:'isolated',opts:['isolated','interim','mandatory','cumulative']},
  {type:'qz1',jp:'（死などを）悼む・嘆き悲しむ',en:'mourn',opts:['mourn','trademark','outsource','benchmark']},

  /* ── 健康・医療（1択クイズ）── */
  {type:'qz1',jp:'吐き気',en:'nausea',opts:['nausea','auditor','franchise','payroll']},
  {type:'qz1',jp:'発疹',en:'rash',opts:['rash','shipment','surplus','turnover']},
  {type:'qz1',jp:'喘息',en:'asthma',opts:['asthma','receipt','deadline','blueprint']},
  {type:'qz1',jp:'糖尿病',en:'diabetes',opts:['diabetes','overtime','signature','inventory']},
  {type:'qz1',jp:'不眠症',en:'insomnia',opts:['insomnia','surplus','payroll','shipment']},
  {type:'qz1',jp:'伝染性の・うつりやすい',en:'infectious',opts:['infectious','quarterly','urgent','bilateral']},
  {type:'qz1',jp:'水疱瘡',en:'chicken pox',opts:['chicken pox','deadline','receipt','trademark']},
  {type:'qz1',jp:'栄養価が高い',en:'nutritious',opts:['nutritious','fiscal','portable','mandatory']},

  /* ── 職業・ビジネス・社会（1択クイズ）── */
  {type:'qz1',jp:'起業家・実業家',en:'entrepreneur',opts:['entrepreneur','blueprint','overtime','subsidy']},
  {type:'qz1',jp:'同僚・職場の人',en:'colleague',opts:['colleague','turnover','shipment','dividend']},
  {type:'qz1',jp:'監督・管理',en:'supervision',opts:['supervision','payroll','surplus','receipt']},
  {type:'qz1',jp:'統合する・合併させる',en:'merge',opts:['merge','inventory','deadline','overtime']},
  {type:'qz1',jp:'解雇する（インフォーマル）',en:'sack',opts:['sack','signature','blueprint','turnover']},
  {type:'qz1',jp:'獣医',en:'vet',opts:['vet','subsidy','receipt','payroll']},
  {type:'qz1',jp:'多言語話者',en:'polyglot',opts:['polyglot','franchise','shipment','surplus']},
  {type:'qz1',jp:'（人種の）隔離・分離',en:'segregation',opts:['segregation','benchmark','deadline','receipt']},
  {type:'qz1',jp:'汚職・腐敗した',en:'corrupt',opts:['corrupt','occasional','durable','interim']},

  /* ── その他・形容詞・副詞（単語入力）── */
  {type:'word_input',jp:'結局は・ついに',en:'eventually'},
  {type:'word_input',jp:'以前に・これまでに',en:'previously'},
  {type:'word_input',jp:'壮大な',en:'magnificent'},
  {type:'word_input',jp:'特徴的な・独特の',en:'distinctive'},
  {type:'word_input',jp:'原産の・先住の',en:'indigenous'},
  {type:'word_input',jp:'予測・予言',en:'prediction'},
  {type:'word_input',jp:'義務',en:'obligation'},
  {type:'word_input',jp:'格闘する・立ち向かう',en:'wrestle'},
  {type:'word_input',jp:'三つ編み',en:'braid'},
  {type:'word_input',jp:'ノンアルコールカクテル',en:'mocktails'},
  {type:'word_input',jp:'幸運な人（口語）',en:'lucky duck'},
  {type:'word_input',jp:'起業家',en:'entrepreneur'},
  {type:'word_input',jp:'同意する・承諾する',en:'consent'},
];
